import { decodeBuf } from '../decode'
import type { BufMeta, UnpackMode } from '../types'

export type WritePlyOptions = {
  /** ascii (default) or binary_little_endian */
  format?: 'ascii' | 'binary_little_endian'
  unpackMode?: UnpackMode
  /** Include non-standard vertex attrs (shadowmask, trailRatio, …). Default true */
  includeCustom?: boolean
  /** Write faces from indices when meshType is Mesh. Default true */
  includeFaces?: boolean
  /** Write line faces (2-index) when meshType is LineSegments. Default true */
  includeLines?: boolean
}

type VertexProp = {
  name: string
  /** float values, length = vertexCount */
  data: Float32Array
}

const STANDARD: Record<string, string[]> = {
  position: ['x', 'y', 'z'],
  normal: ['nx', 'ny', 'nz'],
  uv: ['s', 't'],
  color: ['red', 'green', 'blue'],
}

function expandAttribute(
  id: string,
  interleaved: Float32Array,
  componentSize: number,
  vertexCount: number,
): VertexProp[] {
  const names = STANDARD[id]
  const props: VertexProp[] = []
  for (let c = 0; c < componentSize; c++) {
    const name = names?.[c] ?? (componentSize === 1 ? id : `${id}_${c}`)
    const data = new Float32Array(vertexCount)
    for (let i = 0; i < vertexCount; i++) {
      data[i] = interleaved[i * componentSize + c]!
    }
    props.push({ name, data })
  }
  return props
}

function buildVertexProps(
  meta: BufMeta,
  attributes: Record<string, Float32Array>,
  includeCustom: boolean,
): VertexProp[] {
  const props: VertexProp[] = []
  const orderHint = ['position', 'normal', 'uv', 'color']

  const ids = meta.attributes
    .map((a) => a.id)
    .filter((id) => id !== 'indices')

  const sorted = [
    ...orderHint.filter((id) => ids.includes(id)),
    ...ids.filter((id) => !orderHint.includes(id)),
  ]

  for (const id of sorted) {
    const attrMeta = meta.attributes.find((a) => a.id === id)!
    if (!includeCustom && !STANDARD[id]) continue
    props.push(
      ...expandAttribute(
        id,
        attributes[id]!,
        attrMeta.componentSize,
        meta.vertexCount,
      ),
    )
  }
  return props
}

function facesFromIndices(
  indices: Float32Array,
  meshType: string,
): number[][] {
  const faces: number[][] = []
  if (meshType === 'LineSegments') {
    for (let i = 0; i + 1 < indices.length; i += 2) {
      faces.push([indices[i]!, indices[i + 1]!])
    }
    return faces
  }
  // Mesh / default: triangles
  for (let i = 0; i + 2 < indices.length; i += 3) {
    faces.push([indices[i]!, indices[i + 1]!, indices[i + 2]!])
  }
  return faces
}

function fmtFloat(v: number): string {
  if (!Number.isFinite(v)) return '0'
  // compact but precise enough for DCC round-trip
  return Number(v.toPrecision(9)).toString()
}

/** Encode decoded .buf data as a PLY ArrayBuffer (UTF-8 for ascii). */
export function encodePly(
  meta: BufMeta,
  attributes: Record<string, Float32Array>,
  options: WritePlyOptions = {},
): ArrayBuffer {
  const format = options.format ?? 'ascii'
  const includeCustom = options.includeCustom !== false
  const props = buildVertexProps(meta, attributes, includeCustom)

  const wantFaces =
    (options.includeFaces !== false && meta.meshType === 'Mesh' && meta.indexCount > 0) ||
    (options.includeLines !== false &&
      meta.meshType === 'LineSegments' &&
      meta.indexCount > 0)

  const faces =
    wantFaces && attributes.indices
      ? facesFromIndices(attributes.indices, meta.meshType)
      : []

  const header: string[] = [
    'ply',
    `format ${format} 1.0`,
    `comment generated by ply-to-buf from Lusion .buf`,
    `comment meshType ${meta.meshType}`,
    `comment vertexCount ${meta.vertexCount}`,
    `comment indexCount ${meta.indexCount}`,
  ]
  if (meta.sceneData !== undefined) {
    header.push(`comment sceneData ${JSON.stringify(meta.sceneData)}`)
  }
  for (const a of meta.attributes) {
    header.push(
      `comment attr ${a.id} storage=${a.storageType} pack=${a.needsPack} components=${a.componentSize}`,
    )
  }

  header.push(`element vertex ${meta.vertexCount}`)
  for (const p of props) {
    header.push(`property float ${p.name}`)
  }

  if (faces.length) {
    header.push(`element face ${faces.length}`)
    header.push(`property list uchar int vertex_indices`)
  }
  header.push('end_header')

  if (format === 'ascii') {
    const lines = [...header]
    for (let i = 0; i < meta.vertexCount; i++) {
      const row: string[] = []
      for (const p of props) row.push(fmtFloat(p.data[i]!))
      lines.push(row.join(' '))
    }
    for (const f of faces) {
      lines.push(`${f.length} ${f.map((n) => Math.round(n)).join(' ')}`)
    }
    lines.push('')
    return new TextEncoder().encode(lines.join('\n')).buffer
  }

  // binary_little_endian
  const headerText = header.join('\n') + '\n'
  const headerBytes = new TextEncoder().encode(headerText)
  const vertBytes = meta.vertexCount * props.length * 4
  let faceBytes = 0
  for (const f of faces) faceBytes += 1 + f.length * 4
  const out = new ArrayBuffer(headerBytes.byteLength + vertBytes + faceBytes)
  const view = new Uint8Array(out)
  view.set(headerBytes, 0)
  const dv = new DataView(out)
  let o = headerBytes.byteLength
  for (let i = 0; i < meta.vertexCount; i++) {
    for (const p of props) {
      dv.setFloat32(o, p.data[i]!, true)
      o += 4
    }
  }
  for (const f of faces) {
    dv.setUint8(o, f.length)
    o += 1
    for (const idx of f) {
      dv.setInt32(o, Math.round(idx), true)
      o += 4
    }
  }
  return out
}

/** Decode a .buf and write PLY bytes. */
export function bufToPly(
  buffer: ArrayBuffer,
  options: WritePlyOptions = {},
): { ply: ArrayBuffer; meta: BufMeta } {
  const unpackMode = options.unpackMode ?? 'everswap'
  const { meta, attributes } = decodeBuf(buffer, unpackMode)
  return { ply: encodePly(meta, attributes, options), meta }
}
