import { STORAGE } from './storage'
import type { BufMeta, UnpackMode } from './types'

/** Decode .buf → float attribute map. */
export function decodeBuf(
  buffer: ArrayBuffer,
  unpackMode: UnpackMode = 'everswap',
): {
  meta: BufMeta
  attributes: Record<string, Float32Array>
} {
  const headerLen = new Uint32Array(buffer, 0, 1)[0]!
  const meta = JSON.parse(
    String.fromCharCode(...new Uint8Array(buffer, 4, headerLen)),
  ) as BufMeta

  let offset = 4 + headerLen
  const attributes: Record<string, Float32Array> = {}

  for (const attr of meta.attributes) {
    const count = attr.id === 'indices' ? meta.indexCount : meta.vertexCount
    const info = STORAGE[attr.storageType]
    const raw = new info.Ctor(buffer, offset, count * attr.componentSize)
    const out = new Float32Array(count * attr.componentSize)

    if (attr.needsPack && attr.packedComponents) {
      const size = 1 << (info.bytes * 8)
      const bias = attr.storageType.startsWith('Int') ? size * 0.5 : 0
      const inv = unpackMode === 'schematic' ? 1 / (size - 1) : 1 / size
      let i = 0
      for (let v = 0; v < count; v++) {
        for (let c = 0; c < attr.packedComponents.length; c++) {
          const p = attr.packedComponents[c]!
          out[i] = (raw[i]! + bias) * inv * p.delta + p.from
          i++
        }
      }
    } else {
      out.set(raw as unknown as ArrayLike<number>)
    }

    attributes[attr.id] = out
    offset += count * attr.componentSize * info.bytes
  }

  return { meta, attributes }
}

/** Generate Lusion-style “schematic buffer” Three.js loader snippet. */
export function generateSchematicCode(
  meta: BufMeta,
  options: { includeSceneScript?: boolean; unpackMode?: UnpackMode } = {},
): string {
  const unpackMode = options.unpackMode ?? 'schematic'
  const divider =
    unpackMode === 'schematic' ? '1 / (size - 1)' : '1 / size'

  const lines: string[] = [
    `// Generated by ply-to-buf — Lusion-compatible .buf loader`,
    `// meshType: ${meta.meshType}  vertices: ${meta.vertexCount}  indices: ${meta.indexCount}`,
    `async function loadBuf(url) {`,
    `  const res = await fetch(url);`,
    `  const buffer = await res.arrayBuffer();`,
    `  const headerLen = new Uint32Array(buffer, 0, 1)[0];`,
    `  const meta = JSON.parse(String.fromCharCode(...new Uint8Array(buffer, 4, headerLen)));`,
    `  let offset = 4 + headerLen;`,
    `  const geometry = new THREE.BufferGeometry();`,
    `  const TYPED = {`,
    `    Float32Array, Int8Array, Uint8Array, Int16Array, Uint16Array, Int32Array, Uint32Array,`,
    `  };`,
    `  for (const attr of meta.attributes) {`,
    `    const count = attr.id === 'indices' ? meta.indexCount : meta.vertexCount;`,
    `    const Ctor = TYPED[attr.storageType];`,
    `    const bytes = Ctor.BYTES_PER_ELEMENT;`,
    `    const raw = new Ctor(buffer, offset, count * attr.componentSize);`,
    `    let data = raw;`,
    `    if (attr.needsPack && attr.packedComponents) {`,
    `      const size = 1 << (bytes * 8);`,
    `      const bias = attr.storageType.startsWith('Int') ? size * 0.5 : 0;`,
    `      const inv = ${divider};`,
    `      const out = new Float32Array(count * attr.componentSize);`,
    `      let i = 0;`,
    `      for (let v = 0; v < count; v++) {`,
    `        for (let c = 0; c < attr.packedComponents.length; c++) {`,
    `          const p = attr.packedComponents[c];`,
    `          out[i] = (raw[i] + bias) * inv * p.delta + p.from;`,
    `          i++;`,
    `        }`,
    `      }`,
    `      data = out;`,
    `    }`,
    `    if (attr.id === 'indices') geometry.setIndex(new THREE.BufferAttribute(data, 1));`,
    `    else geometry.setAttribute(attr.id, new THREE.BufferAttribute(data, attr.componentSize));`,
    `    offset += count * attr.componentSize * bytes;`,
    `  }`,
    `  return { geometry, meta };`,
    `}`,
  ]

  if (options.includeSceneScript && meta.sceneData) {
    lines.push(
      ``,
      `// sceneData from PLY comment`,
      `const sceneData = ${JSON.stringify(meta.sceneData, null, 2)};`,
    )
  }

  return lines.join('\n')
}
